# Generated by Django 5.0 on 2024-12-23 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_attribute_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='products.categories'),
        ),
    ]
