# Generated by Django 5.0 on 2024-12-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_attributevalue_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
