# Generated by Django 5.0 on 2024-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productbrand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='placedoder',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placedoder',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placedoder',
            name='shipping_method',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express')], default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='placedoder',
            name='shipping_status',
            field=models.CharField(choices=[('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='In Transit', max_length=50),
        ),
        migrations.AddField(
            model_name='placedoder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placedoder',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Packed', 'Order Packed'), ('Order On The Way', 'Order On The Way'), ('Order Shipped', 'Order Shipped')], default='Order Received', max_length=50),
        ),
    ]
