# Generated by Django 5.0 on 2024-12-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_customeraddress_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='address_line_2',
            field=models.CharField(default='unknown', max_length=250),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(default='unknown', max_length=60),
            preserve_default=False,
        ),
    ]
