# Generated by Django 5.0 on 2025-01-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_customeraddress_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value', 'product')},
        ),
    ]
